# This is a TOML document. Boom.

ver = "1.0.0"
user = "nobody"
pid = "/tmp/msg-api.pid"
dir = "./"
perf = "0.0.0.0:6000"
checkFile = "/data/www/msg-api.html"
log = "/tmp/log/msg-api/"
trace = true
debug = false

[multiHTTP]
    [multiHTTP.outer]
    addrs = ["0.0.0.0:8001"]
    maxListen = 10
    [multiHTTP.inner]
    addrs = ["0.0.0.0:8002"]
    maxListen = 10
    [multiHTTP.local]
    addrs = ["0.0.0.0:8003"]
    maxListen = 10

[rpcClient]
    [rpcClient.managerClient]
    serviceName = "manager"
    etcdAddr = "localhost:2379"
    balancer = "rr"

[redis]
name = "msg-api"
proto = "tcp"
addr = "172.16.0.148:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "10s"
