apiVersion: v1
kind: ReplicationController
metadata:
  name: logic
spec:
  replicas: 1
  selector:
    app: logic
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic
        image: logic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 21000