apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181