
ver = "1.0.0"
logPath = "/tmp/es-job.log"

[kafkaConsumer]
group = "es-job"
topics = ["msg_server_producer"]
offset = true
    [kafkaConsumer.zookeeper]
    root = "/brokers"
    addrs = ["127.0.0.1:2181"]
    timeout = "1s"
