# manager conf

ver = "1.0.0"
logPath = "/tmp/manager.log"

[rpcServer]
proto = "tcp"
addr = "0.0.0.0:24000"

[serviceDiscoveryServer]
serviceName = "manager"
rpcAddr = "127.0.0.1:24000"
etcdAddr = "localhost:2379"
interval = "5s"
ttl = "10s"

[redis]
name = "manager"
proto = "tcp"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
expire = "15s"

[mongoDB]
addrs = "127.0.0.1:27017"
db = "im"
dialTimeout = "1s"
offlineMsgCollection = "offline_msg"

[hbase]
zkAddr = "127.0.0.1:2181"
table = "im"
userFamily = "user"
msgFamily = "msg"

[mysql]
    [mysql.im]
    name = "[im]tcp@127.0.0.1:3306"
    dsn = "root:1@tcp(127.0.0.1:3306)/im?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5 
    idle = 2 


